[assembly: System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("DynamicProxyGenAssembly2")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Abstractions.Data.Fakes")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Abstractions.Data.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Abstractions.Requests.Fakes")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Abstractions.RequestHandlers.Fakes")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Abstractions.RequestHandlers.Tests")]
